### ISSUE TITLE
[BUG] Can't sync Item Stock Levels or Item with Woocommerce

### ISSUE THREAD

**Issue by OmelMedina** [dvdl16/woocommerce_fusion#127]
### Current Behavior

Cannot sync stock level of variant item or sync the item in general. I left the errors down below that I found. One of the issues has to do with an incorrect endpoint url that is being used to modify the stock values. The other seems to be that my variation item id cannot be found on my woocommerce website.  

### Steps To Reproduce

I click on  "Sync this Item's Stock Levels to Woocommerce" and it produces this error in the log.

Status Code not 200

Data in PUT request: 
{'stock_quantity': 1}

Response: 
404
Response Text: 
{"code":"woocommerce_rest_invalid_product_id","message":"To manipulate product variations you should use the \/products\/&lt;product_id&gt;\/variations\/&lt;id&gt; endpoint.","data":{"status":404}}
Request URL: https://example.com/wp-json/wc/v3/products/2025
Request Body: b'{"stock_quantity": 1}'

When I click on "Sync this Item with WooCommerce" it produces this error saying it cannot find the variation product. 

### App Versions
```
{
	"erpnext": "15.38.4",
	"frappe": "15.44.2",
	"print_designer": "1.0.0-dev",
	"woocommerce_fusion": "1.7.4"
}
```
### Route
```
Form/Item/CLH-HDE-50CM2-HT-EU
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/woocommerce_fusion/woocommerce_fusion/tasks/sync_items.py", line 89, in run_item_sync
    sync.run()
  File "apps/woocommerce_fusion/woocommerce_fusion/tasks/sync_items.py", line 174, in run
    raise err
  File "apps/woocommerce_fusion/woocommerce_fusion/tasks/sync_items.py", line 164, in run
    self.get_corresponding_item_or_product()
  File "apps/woocommerce_fusion/woocommerce_fusion/tasks/sync_items.py", line 193, in get_corresponding_item_or_product
    raise ValueError(
ValueError: No WooCommerce Product found with ID 2025 on example.com

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"item_code": "CLH-HDE-50CM2-HT-EU"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/woocommerce_fusion.tasks.sync_items.run_item_sync",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "ValueError: No WooCommerce Product found with ID 2025 on example.com",
	"exc_type": "ValueError",
	"_exc_source": "woocommerce_fusion (app)"
}
```

### Expected Behavior

The Item's are variations of a variable product that has been created. I can see all these items in the Woocommerce Orders Doctype. Syncing the Item's Price to WooCommerce just fine. I can update things inside the Woocommerce Products Virtual Doctype and they will reflect on WooCommerce. I am assuming this isn't an issue with a simple product that has no variations. It seems like the endpoint is incorrect and thus it returns an error. This particular variation has a slug that I never set. The permalink structure for id = 2025 is correct and does take me to the variation of my product online successfully. But I don't believe that is the endpoint that should be used for modification of the stock qty. The products exist since they were created from WooCommerce originally and then I created them individually in ERPnext using the "Sync this Item to ERPnext' button. 

Am I missing something?

### Environment and Versions

```markdown
- Frappe Version: 
- ERPNext Version: 
- Custom App Version:
```

### Operating System

Other

**Comment by kossanah** [comment]
It looks like your Woocommerce API is not working, can you test it directly with Postman.?
However, I noticed that if a product in woocommerce does not have  "Managed stock" active, the quantity sync does not work. I fixed this in a PR

**Comment by OmelMedina** [comment]
Hi @kossanah,

I'm not familiar with testing using postman. I'm using this live with my wordpress site. My store is hidden and private since I'm not done building. But that doesn't seem to stop the Woocommerce API from working. All my variations have "Managed Stock" and no success there. 

Is it because my permalink structure for the product variations need to be configured a certain way? I can sync the Item Price just fine which should be using a similar endpoint no?
