### ISSUE TITLE
[BUG] Item variant how to?

### ISSUE THREAD

**Issue by ashish-greycube** [dvdl16/woocommerce_fusion#128]
### Current Behavior

I wish to create say Tshirt (i.e. Has variant or template item) and with item attributes as red and green. Red and  Green are real items with stock and price
Wider question is , is this type of sych is supported by this integration app?

### Steps To Reproduce

Template item
![image](https://github.com/user-attachments/assets/fce04ded-6e28-474c-ba7c-dbfa4d6df055)
![image](https://github.com/user-attachments/assets/d10153ff-6ae1-455d-9e60-aaaafafb43e4)
![image](https://github.com/user-attachments/assets/9c8c8ddc-2a5a-4eba-8ba7-0d4cb0ca8d5f)

Item
![image](https://github.com/user-attachments/assets/5be11538-15d6-42aa-b4fe-c27a96e00aef)
![image](https://github.com/user-attachments/assets/9036a708-3335-4f33-84e2-3bf0a5e90561)

Note, the WooCommerce ID gets populated i.e.
for tshirt template : WooCommerce ID : 68895
for red tshirt : WooCommerce ID : 68897
for green tshirt : WooCommerce ID :68896

On woocomerce side, you see only 68895 i.e. template
![image](https://github.com/user-attachments/assets/be3e5444-5370-47c4-99f8-fb0d1d068230)
Other ids 68897 and 68896 are consumed but they donot show up on woocomerce side

On ERPNext side, when we try to sych say  red tshirt : WooCommerce ID : 68897
id not found error

### App Versions
```
{
	"erpnext": "15.41.1",
	"frappe": "15.47.2",
	"woocommerce_fusion": "1.7.4"
}
```
### Route
```
Form/Item/Polo Tshirt-RED
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1781, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/woocommerce_fusion/woocommerce_fusion/tasks/sync_items.py", line 89, in run_item_sync
    sync.run()
  File "apps/woocommerce_fusion/woocommerce_fusion/tasks/sync_items.py", line 174, in run
    raise err
  File "apps/woocommerce_fusion/woocommerce_fusion/tasks/sync_items.py", line 164, in run
    self.get_corresponding_item_or_product()
  File "apps/woocommerce_fusion/woocommerce_fusion/tasks/sync_items.py", line 193, in get_corresponding_item_or_product
    raise ValueError(
ValueError: No WooCommerce Product found with ID 68897 on staging.septillion.co.th

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"item_code": "Polo Tshirt-RED"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/woocommerce_fusion.tasks.sync_items.run_item_sync",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "ValueError: No WooCommerce Product found with ID 68897 on staging.septillion.co.th",
	"exc_type": "ValueError",
	"_exc_source": "woocommerce_fusion (app)"
}
```

### Expected Behavior

Item variant sync should work
If there is any documentation on how to do it would be really helpful

### Environment and Versions

```markdown
- Frappe Version: 
- ERPNext Version: 
- Custom App Version:
```

### Operating System

Other

### What browsers are you seeing the problem on?

Chrome

**Comment by OmelMedina** [comment]
Hey @ashish-greycube,

I am working with the variants myself. I posted an issue two days ago with variants. While you have a slightly different issue, I do get a similar error saying that it cannot find the woocommerce ID for my product variant. I created them in Woocommerce and then it appeared in the Woocommerce Product Doctype. I can see my template item and the variants to that item. I created the variants from that doctype. But whenever I try to sink the Stock Levels for a variant. I get an issue saying it cannot find my variant ID on Woocommerce. The Woocommerce Doctype definitely does show each variant. I have even made price adjustments and description changes with ERPnext successfully updating the Woocommerce variant.

One of my issues was that the endpoint for the variant seems incorrect when you click on the Sync Item Stock Levels. It should be the same endpoint that allows me to modify the prices and description of each variant. Not sure exactly what the issue is myself. I'll look into the code when I have more time this week. I'm sure @dvdl16 has an idea of what might be happening

**Comment by dvdl16** [comment]
@Glitch-Trap-1 @ashish-greycube thank you for the detailed information. I haven't added any tests for stock sync with variants, I'll look into this soon

**Comment by ashish-greycube** [comment]
@dvdl16 as per you above comment it appears to me variant is working
Can you please guide to some doc on how to do it correctly i.e. variant should be created in which system first? and any settings?
Thanks

**Comment by MartinFulgueiras** [comment]
@ashish-greycube It would be helpful if you posted the Variations section in woocommerce (it appears in the image you posted) to see that effectively it hasn't created the variations in WC.

**Comment by jslocomotor** [comment]
I'm having trouble setting up variants as well. My template item has been created in WooCommerce, but variants are not getting created:

![Image](https://github.com/user-attachments/assets/dfc197f1-dc75-4e16-b1d3-93dc3cff6c36)

![Image](https://github.com/user-attachments/assets/347a83a9-2d69-4d68-9144-4696cfb9e947)

![Image](https://github.com/user-attachments/assets/0815fd53-ac69-4670-b911-6ae5ffc103f3)

Variant attributes were created correctly.

If I'm creating a new variant in ERPNext it gets the same WooCommerce ID as the template, is that expected?
When creating a variant inside WooCommerce it counts the variants ID up.

![Image](https://github.com/user-attachments/assets/d17649ce-b43e-4966-8111-ff9d0d44512d)

**Comment by alphaomegaphi** [comment]
Hi @dvdl16 hope you are doing well.

I am too able to confirm the issue mentioned by @jslocomotor above. I tried a slightly different approach as described below:

1. Created an Item Template in ERPNext, called "Product Test", with a woocommerce server in the child table, and ID left blank. Has Variant checked and added two attributes: Colour and Size attributes.
2. Once template created in ERPNext, then a Variable product "Product Test" was created successfully over WC. All attribute elements were also added in the Attribute tab.
3. No WC variants created at the moment, which is expected.
4. Still WC, click generate variants in the variations tab. Copy the ID of the variant Colour: Black/Size: M.
5. Back in ERPNext, created a single variant for Colour = Black, Size = M. Added the woocommerce server and variantion ID from WC and checked the Sync With woocommerce. Then Click Sync this item with Woocommerce action, and got this error:

![Image](https://github.com/user-attachments/assets/9ee8ce9a-2f97-449c-ba4e-a926d98699dc)

![Image](https://github.com/user-attachments/assets/48d76bfa-502b-4e92-906d-6fb0137dc9f0)

![Image](https://github.com/user-attachments/assets/143c5fac-3f3f-4181-b1bd-9d04d6ec91ae)

I also tried having ERPNext creating the variantion in WC (by not filling the ID in the woocomerce server child table) but same error as shwon above. Same as @jslocomotor, I also noticed the variations were not shown in WC Variations tab, but the ID itself was created and assigned to the woocommerce server child table. 

The request log shows response 200, but without payload returned for the Variation ID, why is not returning the variations data?

**Comment by jslocomotor** [comment]
Hi, any update on this? @dvdl16 could you give us a little hint what is implemented from your side and what we can do to help you troubleshoot? Also adding this in the documentation would be helpfull.

**Comment by alphaomegaphi** [comment]
Hi @jslocomotor  the issue is that the variation is created in "draft" by default because WC Fusion is not passing that attribute on variation creation. So by adding the variation status in the payload passed to WC, it creates the variation in "published" status. There is a specific function in the sync_items.py file that handles WC product creation. Hope @dvdl16 adds the fix in the next release.

**Comment by jslocomotor** [comment]
Sorry to ask again, but could this be implemented soon? This would be very helpful. I can't imagine a webshop without product variants, right?
