### ISSUE TITLE
[BUG] KeyError: 'WooCommerce payment method cod not found in WooCommerce Server'

### ISSUE THREAD

**Issue by newhub-spec** [dvdl16/woocommerce_fusion#140]
### Current Behavior

After order is placed in Woocommerce, it is fetched in the ERPNext. When we try to sync manually from ERPNext woocommerce order, it produces the error of not finding Cash on Delivery method. The method is correctly enabled with available shipping zones. 

### Steps To Reproduce

1. Place order in Woocommerce
2. See it from the ERPNext Woocommerce order list
3. Manually sync from Actions>Sync this order with ERPNext

### Expected Behavior

The order should be synced without error.

### Anything else?

Traceback (most recent call last):
  File "apps/woocommerce_fusion/woocommerce_fusion/tasks/sync_sales_orders.py", line 139, in run
    self.sync_wc_order_with_erpnext_order()
  File "apps/woocommerce_fusion/woocommerce_fusion/tasks/sync_sales_orders.py", line 197, in sync_wc_order_with_erpnext_order
    self.create_sales_order(self.woocommerce_order)
  File "apps/woocommerce_fusion/woocommerce_fusion/tasks/sync_sales_orders.py", line 439, in create_sales_order
    self.create_and_link_payment_entry(wc_order, new_sales_order)
  File "apps/woocommerce_fusion/woocommerce_fusion/tasks/sync_sales_orders.py", line 272, in create_and_link_payment_entry
    raise KeyError(
KeyError: 'WooCommerce payment method cod not found in WooCommerce Server'

Sales Order Data: 

WC Product Data 
{'name': 'example.xyz~1031', 'owner': None, 'creation': None, 'modified': '2024-12-15T03:06:55', 'modified_by': None, 'docstatus': 0, 'idx': 0, 'woocommerce_server': 'example.xyz', 'id': 1031, 'parent_id': 0, 'number': '1031', 'order_key': 'wc_order_5l7D5Wrz5B5oe', 'created_via': 'checkout', 'version': '9.4.3', 'status': 'processing', 'currency': 'XYZ', 'date_created': '2024-12-15T03:06:53', 'date_created_gmt': '2024-12-14T21:06:53', 'date_modified': '2024-12-15T03:06:55', 'date_modified_gmt': '2024-12-14T21:06:55', 'discount_total': '0.00', 'discount_tax': '0.00', 'shipping_total': '10.00', 'shipping_tax': '0.00', 'cart_tax': '0.00', 'total': '1020.00', 'total_tax': '0.00', 'prices_include_tax': 0, 'customer_id': 1, 'customer_ip_address': '165.xxx.37.xx', 'customer_user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36', 'customer_note': '', 'billing': '{"first_name": "John", "last_name": "", "company": "", "address_1": "Test House", "address_2": "", "city": "", "state": "BD-13", "postcode": "", "country": "", "email": "demo@test.com", "phone": "0123456789"}', 'shipping': '{"first_name": "", "last_name": "", "company": "", "address_1": "", "address_2": "", "city": "", "state": "", "postcode": "", "country": "", "phone": ""}', 'payment_method': 'cod', 'payment_method_title': 'Cash on delivery', 'transaction_id': '', 'date_paid': None, 'date_paid_gmt': None, 'date_completed': None, 'date_completed_gmt': None, 'cart_hash': 'ca4a0c80e8eee4079080bc44426b', 'meta_data': '[{"id": 711, "key": "_wc_order_attribution_device_type", "value": "Desktop"}, {"id": 704, "key": "_wc_order_attribution_referrer", "value": "https://example.xyz/wp-admin/admin.php?page=wc-settings&tab=advanced&section=webhooks&edit-webhook=1"}, {"id": 709, "key": "_wc_order_attribution_session_count", "value": "2"}, {"id": 706, "key": "_wc_order_attribution_session_entry", "value": "https://example.xyz/shop/"}, {"id": 708, "key": "_wc_order_attribution_session_pages", "value": "3"}, {"id": 707, "key": "_wc_order_attribution_session_start_time", "value": "2024-12-14 19:28:21"}, {"id": 703, "key": "_wc_order_attribution_source_type", "value": "typein"}, {"id": 710, "key": "_wc_order_attribution_user_agent", "value": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"}, {"id": 705, "key": "_wc_order_attribution_utm_source", "value": "(direct)"}, {"id": 702, "key": "_wcf_checkout_id", "value": "710"}, {"id": 701, "key": "_wcf_flow_id", "value": "709"}, {"id": 698, "key": "is_vat_exempt", "value": "no"}]', 'line_items': '[{"id": 86, "name": "Test and Body Shaper - XL, Black", "product_id": 541, "variation_id": 597, "quantity": 1, "tax_class": "", "subtotal": "1010.00", "subtotal_tax": "0.00", "total": "1010.00", "total_tax": "0.00", "taxes": [], "meta_data": [{"id": 690, "key": "size", "value": "XL", "display_key": "Size", "display_value": "XL"}, {"id": 691, "key": "color", "value": "Black", "display_key": "Color", "display_value": "Black"}], "sku": "", "price": 1010, "image": {"id": 603, "src": "https://example.xyz/wp-content/uploads/2024/12/37341eba-7abd-4d98-84ca-1412f5c99398.jpg"}, "parent_name": "Test and Body Shaper"}]', 'tax_lines': '[]', 'shipping_lines': '[{"id": 87, "method_title": "\\u0u8\\u00be\\u0895\\u09je \\u07b8\\u09lf\\u899f\\u09bi", "method_id": "flat_rate", "instance_id": "1", "total": "10.00", "total_tax": "0.00", "taxes": [], "meta_data": [{"id": 697, "key": "Items", "value": "Test and Body Shaper - XL, Black &times; 1", "display_key": "Items", "display_value": "Test and Body Shaper - XL, Black &times; 1"}]}]', 'fee_lines': '[]', 'coupon_lines': '[]', 'refunds': '[]', 'set_paid': 0, 'shipment_trackings': None, 'doctype': 'WooCommerce Order'})

### Environment and Versions

```markdown
"erpnext": "15.45.5",
"frappe": "15.50.0",
"ecommerce_integrations": "1.20.1",
"payments": "0.0.1",
"webshop": "0.0.1",
"woocommerce_fusion": "1.8.0"
```

### Operating System

Other

### What browsers are you seeing the problem on?

Chrome

**Comment by dvdl16** [comment]
@newhub-spec Thanks for raising the issue. Is the "Enable Payments Sync" checkbox checked under **WooCommerce Server** > "Sales Orders"? If so, do you have mappings defined in " Map Bank Accounts to Payment Methods " and " Map GL Accounts to Payment Methods "?

**Comment by mepoland** [comment]
I came across this issue while configuring WC Fusion for the first time. I haven't encountered any errors yet, but I think I see what the OP is getting at. By definition, `cod` (Collect On Delivery) means the customer is NOT paying when they place the order. They are placing the order (so a Sales Invoice should be created), but they are postponing payment (so NO Payment Entry) should be created).
For my use case, 95% of orders are paid at the same time the order is placed, but 5% are `cod`. I want the "Enable Payments Sync" function for the 95% only.
Perhaps one way to solve this is to allow a blank mapping of the `cod` payment method in WooCommerce, and have Fusion skip PE creation for blank mappings? E.g.:
```{
   "woocommerce_payments": "WooPayments - WooPayments",
   "cheque": "Business Checking - My Bank",
   "cod": "",
   "bacs": "Business Checking - My Bank"
}```

**Comment by dvdl16** [comment]
@mepoland the Payment Entry will only be created if the following conditions are true:

- `WooCommerce Order` > `Payment Method` is set 
**and**
- `WooCommerce Order` > `Date Paid` is set (unless `Ignore empty 'Date Paid' field on WooCommerce Orders` is set on `WooCommerce Server`

(Ref https://github.com/dvdl16/woocommerce_fusion/blob/d09cd7748d36dd7e152bec73ddfdb83f2a507918/woocommerce_fusion/tasks/sync_sales_orders.py#L269C17-L269C31)

WooCommerce typically doesn't set these fields when the payment method is `cod` - so your use case should work fine. If not, let me know?

That said, I do see now that it is confusing that you still have to define a mapping for `cod`, even though it's not relevant for Payment Entry creation, perhaps I can update the documentation to make this clear
