### ISSUE TITLE
[BUG] synch order fails due to SynchroniseSalesOrder' object has no attribute 'customer'

### ISSUE THREAD

**Issue by ashish-greycube** [dvdl16/woocommerce_fusion#148]
### Current Behavior

```
### App Versions
```
{
	"erpnext": "15.36.2",
	"frappe": "15.42.0",
	"hrms": "15.30.0",
	"payments": "0.0.1",
	"woocommerce_fusion": "1.10.0"
}
```
### Route
```
Form/WooCommerce Order/xxx~72616
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/woocommerce_fusion/woocommerce_fusion/tasks/sync_sales_orders.py", line 63, in run_sales_order_sync
    sync.run()
  File "apps/woocommerce_fusion/woocommerce_fusion/tasks/sync_sales_orders.py", line 143, in run
    raise err
  File "apps/woocommerce_fusion/woocommerce_fusion/tasks/sync_sales_orders.py", line 139, in run
    self.sync_wc_order_with_erpnext_order()
  File "apps/woocommerce_fusion/woocommerce_fusion/tasks/sync_sales_orders.py", line 197, in sync_wc_order_with_erpnext_order
    self.create_sales_order(self.woocommerce_order)
  File "apps/woocommerce_fusion/woocommerce_fusion/tasks/sync_sales_orders.py", line 419, in create_sales_order
    customer_docname = self.create_or_link_customer_and_address(wc_order)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/woocommerce_fusion/woocommerce_fusion/tasks/sync_sales_orders.py", line 538, in create_or_link_customer_and_address
    self.create_or_update_address(wc_order)
  File "apps/woocommerce_fusion/woocommerce_fusion/tasks/sync_sales_orders.py", line 635, in create_or_update_address
    "Customer", self.customer.name, fields=["name", "is_primary_address", "is_shipping_address"]
                ^^^^^^^^^^^^^
AttributeError: 'SynchroniseSalesOrder' object has no attribute 'customer'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"woocommerce_order_name": "septillion.co.th~72616"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/woocommerce_fusion.tasks.sync_sales_orders.run_sales_order_sync",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "AttributeError: 'SynchroniseSalesOrder' object has no attribute 'customer'",
	"exc_type": "AttributeError",
	"_exc_source": "woocommerce_fusion (app)",
	"_server_messages": "[\"{\\\"message\\\": \\\"Could not find Customer Group:  \\\", \\\"title\\\": \\\"Message\\\", \\\"indicator\\\": \\\"red\\\", \\\"raise_exception\\\": 1, \\\"__frappe_exc_id\\\": \\\"9b9427c17396c241c4e53d3465e866ae3b3959834a0f4ebd44a344c4\\\"}\"]"
}
```
```

### Steps To Reproduce

Go to WooCommerce Order and open any order. Click on action "Synch this order with ERPNext"
It gives above error
Note the error is irrespective of address option
![image](https://github.com/user-attachments/assets/2921842a-db5e-476a-838b-8d1717508150)

### Expected Behavior

Order synch should work

### Environment and Versions

```markdown
ERPNext: v15.36.2 (version-15)
Frappe Framework: v15.42.0 (version-15)
WooCommerce Fusion: v1.10.0 (version-15)
```

### Operating System

Other

### What browsers are you seeing the problem on?

Chrome

**Comment by ashish-greycube** [comment]
To add further to above, note: this happens when selling settings has no default customer group defined
![image](https://github.com/user-attachments/assets/b1b9baaf-6674-4a24-9847-3f05fecd05ad)

**Comment by dvdl16** [comment]
Thanks for all the details @ashish-greycube. 

Can you check if there is another error in your Error Log just before the error you posted? Or perhaps any related Error Logs? Something goes wrong when it's trying to save the customer record, so I'm trying to get more information on what scenario will cause this

**Comment by ashish-greycube** [comment]
@dvdl16 it started working once i had customer group set
The related error for customer group is below

```
Traceback (most recent call last):
  File "apps/woocommerce_fusion/woocommerce_fusion/tasks/sync_sales_orders.py", line 532, in create_or_link_customer_and_address
    customer.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 359, in _save
    return self.insert()
           ^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 283, in insert
    self._validate_links()
  File "apps/frappe/frappe/model/document.py", line 930, in _validate_links
    frappe.throw(_("Could not find {0}").format(msg), frappe.LinkValidationError)
  File "apps/frappe/frappe/__init__.py", line 652, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 617, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 568, in _raise_exception
    raise exc
frappe.exceptions.LinkValidationError: Could not find Customer Group:  


Customer Data{'name': None, 'owner': 'Administrator', 'creation': '2024-12-23 16:18:17.577915', 'modified': '2024-12-23 16:18:17.577915', 'modified_by': 'Administrator', 'docstatus': 0, 'idx': 0, 'woocommerce_identifier': 'arthur.hamilton@gmail.com', 'woocommerce_is_guest': 0, 'woocommerce_id': None, 'naming_series': 'CUST-.YYYY.-', 'salutation': None, 'customer_name': 'Arthur Hamilton', 'customer_type': 'Individual', 'customer_group': None, 'territory': 'Thailand ประเทศไทย', 'gender': None, 'lead_name': None, 'opportunity_name': None, 'prospect_name': None, 'account_manager': None, 'image': None, 'default_currency': None, 'default_bank_account': None, 'default_price_list': None, 'is_internal_customer': 0, 'represents_company': None, 'market_segment': None, 'industry': None, 'customer_pos_id': None, 'website': None, 'language': 'en', 'customer_details': None, 'customer_primary_address': None, 'primary_address': None, 'customer_primary_contact': None, 'mobile_no': None, 'email_id': None, 'tax_id': None, 'tax_category': None, 'tax_withholding_category': None, 'payment_terms': 'เงินสด โอนบัญชี', 'loyalty_program': None, 'loyalty_program_tier': None, 'default_sales_partner': None, 'default_commission_rate': 0.0, 'so_required': 0, 'dn_required': 0, 'is_frozen': 0, 'disabled': 0, 'woocommerce_server': None, 'doctype': 'Customer', 'companies': [], 'portal_users': [], 'accounts': [], 'sales_team': [], 'credit_limits': [], '__islocal': True, '__unsaved': 1}
```
